development: &default
  adapter: postgresql
  pool: 5
  timeout: 5000
  host: localhost
  encoding: UTF-8
  database: realism
  username: adminxs3bdv6
  password: gdJnwJM5RqkJ

test:
  <<: *default
  database: realism
  min_messages: warning

production:
  <<: *default
  database: realism
